Added tab navigation and pressing return key to join/host
jilleJr/TellMe pull request #18
Opened 2022-02-13 21:16 UTC by Alexamakans

- Added `TabSelection` script.
  - Apply to any object in the scene to allow downwards UI navigation using the TAB key.
  - Currently applied to the Canvas.
- Added `OnSubmitScript` script.
  - Workaround for missing `OnSubmit` event (Only `OnEndEdit` available, which triggers on focus loss as well).

Closes #15

2022-02-14 18:52 UTC, jilleJr requested changes

2022-02-14 18:52 UTC, jilleJr commented on Assets/Scripts/HostOrJoinScene/OnSubmitScript.cs
> +    public class OnSubmitEvent : UnityEvent<string> { }
nit: Please place nested types at the bottom of the parent type.

2022-02-14 18:52 UTC, jilleJr commented on Assets/Scripts/HostOrJoinScene/TabSelection.cs
> +            target = system.currentSelectedGameObject?.GetComponent<Selectable>().FindSelectableOnDown();
These lines can be merged.

```suggestion
            var target = system.currentSelectedGameObject?.GetComponent<Selectable>().FindSelectableOnDown();
```

2022-02-16 18:48 UTC, Alexamakans commented on Assets/Scripts/HostOrJoinScene/TabSelection.cs
> +            target = system.currentSelectedGameObject?.GetComponent<Selectable>().FindSelectableOnDown();
Right, remember that being a thing before now that you mentioned it 👍🏻

2022-02-16 19:01 UTC, jilleJr approved these changes

2022-02-16 20:02 UTC, merged